### ISSUE TITLE
link standaardenregister vanuit vocabularium

### ISSUE THREAD

**Issue by samuvack** [Informatievlaanderen/OSLOthema-DigitaleWatermeter#11]
De link https://data.vlaanderen.be/standaarden/kandidaatstandaard/applicatieprofiel-digitalewatermeter.html onder Standaardenregister
dient nog geüpdatet worden vanuit het vocabularium Digitale Watermeter (https://data.vlaanderen.be/ns/DigitaleWatermeter/)

**Comment by bjdmeest** [comment]
De detailpagina's https://data.vlaanderen.be/standaarden/vocabularium-nutsvoorzieningen-meters en https://data.vlaanderen.be/standaarden/applicatieprofiel-digitale-watermeter staan nu correct online
