### ISSUE TITLE
dcat:Collectie

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-DigitaleWatermeter#13]
In het uml-diagram staat de klasse dcat:Collectie met dcat:Dataset als subklasse.
In de tekst van het applicatieprofiel is dit een prov:Collection met dcat:Dataset als subklasse.

Volgens het dcat vocabularium is een dcat:Dataset een collectie van data. 
Volgens dit applicatieprofiel is een prov:Collection een groep van datasets en tgv. de subclassing is iedere dcat:Dataset een groep van datasets.

Wat is hiervan de bedoeling?

**Comment by gezever** [comment]
![Screenshot from 2024-09-26 08-52-58](https://github.com/user-attachments/assets/e6facad8-1caa-49a4-b3c8-d7a5b8468dee)

**Comment by bjdmeest** [comment]
Dit is inderdaad verwarrend en niet nodig voor het AP. We hebben deze complexiteit laten vallen.
