### ISSUE TITLE
vocablarium zonder rdf

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-DigitaleWatermeter#15]
$ curl -L -H 'Accept: text/turtle' https://data.vlaanderen.be/ns/nutsvoorzieningen/meters
404 Not Found
$ curl -L  https://data.vlaanderen.be/ns/nutsvoorzieningen/meters.ttl
404 Not Found

**Comment by bjdmeest** [comment]
Dit is ondertussen gefixt
